name: Budowa obrazu serwera i wysłanie do Docker Hub

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**.md'

jobs:
  zbuduj_serwer:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Ustawianie QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Ustawianie Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Zaloguj się do Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Zbuduj i wyślij
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/test:latest
